// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huxrgyilqirjpazjvbbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1eHJneWlscWlyanBhemp2YmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNTc1OTQsImV4cCI6MjA2NDkzMzU5NH0.Tc37j5dtI2Eg6aae3TqXhcXratITyERzEbjVvdTPW_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);